// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: grpcapi/pb/service.proto

// Package rostam.v1 is the gRPC surface over Rostam's vector/RAG operations.
// It mirrors the REST API (httpapi) and dispatches into the same op registry —
// a second transport, not new engine logic. The recursive metadata filter and
// the tagged metadata Value union are carried as JSON strings (filter_json /
// metadata_json / key_json) rather than re-modeled in protobuf, reusing the
// same JSON contract the binary wire codecs already use.
//
// The service is split into its own file/package (grpcsvc) from the message
// definitions in rostam.proto (package pb) so that a caller who only needs
// the protobuf MESSAGES (e.g. the Go client, which speaks the binary TCP
// protocol and only borrows QuerySpec's wire encoding) does not transitively
// pull in google.golang.org/grpc.

package grpcsvc

import (
	pb "github.com/rostamlabs/rostam/sdk/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_grpcapi_pb_service_proto protoreflect.FileDescriptor

const file_grpcapi_pb_service_proto_rawDesc = "" +
	"\n" +
	"\x18grpcapi/pb/service.proto\x12\trostam.v1\x1a\x17grpcapi/pb/rostam.proto2\x80'\n" +
	"\rVectorService\x12=\n" +
	"\x06Health\x12\x18.rostam.v1.HealthRequest\x1a\x19.rostam.v1.HealthResponse\x12[\n" +
	"\x10CreateCollection\x12\".rostam.v1.CreateCollectionRequest\x1a#.rostam.v1.CreateCollectionResponse\x12U\n" +
	"\x0eDropCollection\x12 .rostam.v1.DropCollectionRequest\x1a!.rostam.v1.DropCollectionResponse\x12=\n" +
	"\x06Upsert\x12\x18.rostam.v1.UpsertRequest\x1a\x19.rostam.v1.UpsertResponse\x12=\n" +
	"\x06Delete\x12\x18.rostam.v1.DeleteRequest\x1a\x19.rostam.v1.DeleteResponse\x124\n" +
	"\x03Get\x12\x15.rostam.v1.GetRequest\x1a\x16.rostam.v1.GetResponse\x12C\n" +
	"\bGetBatch\x12\x1a.rostam.v1.GetBatchRequest\x1a\x1b.rostam.v1.GetBatchResponse\x12F\n" +
	"\n" +
	"SetPayload\x12\x1c.rostam.v1.SetPayloadRequest\x1a\x1a.rostam.v1.PayloadResponse\x12L\n" +
	"\x10OverwritePayload\x12\x1c.rostam.v1.SetPayloadRequest\x1a\x1a.rostam.v1.PayloadResponse\x12T\n" +
	"\x11DeletePayloadKeys\x12#.rostam.v1.DeletePayloadKeysRequest\x1a\x1a.rostam.v1.PayloadResponse\x12J\n" +
	"\fClearPayload\x12\x1e.rostam.v1.ClearPayloadRequest\x1a\x1a.rostam.v1.PayloadResponse\x12=\n" +
	"\x06Search\x12\x18.rostam.v1.SearchRequest\x1a\x19.rostam.v1.SearchResponse\x12E\n" +
	"\n" +
	"SearchDocs\x12\x18.rostam.v1.SearchRequest\x1a\x1d.rostam.v1.SearchDocsResponse\x12O\n" +
	"\fSearchGroups\x12\x1e.rostam.v1.SearchGroupsRequest\x1a\x1f.rostam.v1.SearchGroupsResponse\x12C\n" +
	"\fHybridSearch\x12\x18.rostam.v1.HybridRequest\x1a\x19.rostam.v1.SearchResponse\x12I\n" +
	"\n" +
	"TextSearch\x12\x1c.rostam.v1.TextSearchRequest\x1a\x1d.rostam.v1.SearchDocsResponse\x12K\n" +
	"\x10HybridTextSearch\x12\x1c.rostam.v1.HybridTextRequest\x1a\x19.rostam.v1.SearchResponse\x12G\n" +
	"\vVectorQuery\x12\x1d.rostam.v1.VectorQueryRequest\x1a\x19.rostam.v1.SearchResponse\x12Q\n" +
	"\x10NamedVectorQuery\x12\".rostam.v1.NamedVectorQueryRequest\x1a\x19.rostam.v1.SearchResponse\x12K\n" +
	"\rMVVectorQuery\x12\x1f.rostam.v1.MVVectorQueryRequest\x1a\x19.rostam.v1.SearchResponse\x12U\n" +
	"\x0eDeleteByFilter\x12 .rostam.v1.DeleteByFilterRequest\x1a!.rostam.v1.DeleteByFilterResponse\x12@\n" +
	"\aResplit\x12\x19.rostam.v1.ResplitRequest\x1a\x1a.rostam.v1.ResplitResponse\x12U\n" +
	"\x0eResplitCleanup\x12 .rostam.v1.ResplitCleanupRequest\x1a!.rostam.v1.ResplitCleanupResponse\x12@\n" +
	"\aReshard\x12\x19.rostam.v1.ReshardRequest\x1a\x1a.rostam.v1.ReshardResponse\x12O\n" +
	"\fReshardAbort\x12\x1e.rostam.v1.ReshardAbortRequest\x1a\x1f.rostam.v1.ReshardAbortResponse\x12M\n" +
	"\x12MVCreateCollection\x12\x1a.rostam.v1.MVCreateRequest\x1a\x1b.rostam.v1.MVCreateResponse\x12G\n" +
	"\x10MVDropCollection\x12\x18.rostam.v1.MVDropRequest\x1a\x19.rostam.v1.MVDropResponse\x12:\n" +
	"\x05MVAdd\x12\x17.rostam.v1.MVAddRequest\x1a\x18.rostam.v1.MVAddResponse\x12C\n" +
	"\bMVSearch\x12\x1a.rostam.v1.MVSearchRequest\x1a\x1b.rostam.v1.MVSearchResponse\x12L\n" +
	"\x0eMVHybridSearch\x12\x1a.rostam.v1.MVHybridRequest\x1a\x1e.rostam.v1.NamedSearchResponse\x12C\n" +
	"\bMVScroll\x12\x1a.rostam.v1.MVScrollRequest\x1a\x1b.rostam.v1.MVScrollResponse\x12C\n" +
	"\bMVDelete\x12\x1a.rostam.v1.MVDeleteRequest\x1a\x1b.rostam.v1.MVDeleteResponse\x12:\n" +
	"\x05MVGet\x12\x17.rostam.v1.MVGetRequest\x1a\x18.rostam.v1.MVGetResponse\x12I\n" +
	"\n" +
	"MVGetBatch\x12\x1c.rostam.v1.MVGetBatchRequest\x1a\x1d.rostam.v1.MVGetBatchResponse\x12H\n" +
	"\fMVSetPayload\x12\x1c.rostam.v1.SetPayloadRequest\x1a\x1a.rostam.v1.PayloadResponse\x12N\n" +
	"\x12MVOverwritePayload\x12\x1c.rostam.v1.SetPayloadRequest\x1a\x1a.rostam.v1.PayloadResponse\x12V\n" +
	"\x13MVDeletePayloadKeys\x12#.rostam.v1.DeletePayloadKeysRequest\x1a\x1a.rostam.v1.PayloadResponse\x12L\n" +
	"\x0eMVClearPayload\x12\x1e.rostam.v1.ClearPayloadRequest\x1a\x1a.rostam.v1.PayloadResponse\x12B\n" +
	"\tMVResplit\x12\x19.rostam.v1.ResplitRequest\x1a\x1a.rostam.v1.ResplitResponse\x12W\n" +
	"\x10MVResplitCleanup\x12 .rostam.v1.ResplitCleanupRequest\x1a!.rostam.v1.ResplitCleanupResponse\x12B\n" +
	"\tMVReshard\x12\x19.rostam.v1.ReshardRequest\x1a\x1a.rostam.v1.ReshardResponse\x12Q\n" +
	"\x0eMVReshardAbort\x12\x1e.rostam.v1.ReshardAbortRequest\x1a\x1f.rostam.v1.ReshardAbortResponse\x12L\n" +
	"\vNamedCreate\x12\x1d.rostam.v1.NamedCreateRequest\x1a\x1e.rostam.v1.NamedCreateResponse\x12F\n" +
	"\tNamedDrop\x12\x1b.rostam.v1.NamedDropRequest\x1a\x1c.rostam.v1.NamedDropResponse\x12L\n" +
	"\vNamedUpsert\x12\x1d.rostam.v1.NamedUpsertRequest\x1a\x1e.rostam.v1.NamedUpsertResponse\x12L\n" +
	"\vNamedSearch\x12\x1d.rostam.v1.NamedSearchRequest\x1a\x1e.rostam.v1.NamedSearchResponse\x12X\n" +
	"\x11NamedSparseSearch\x12#.rostam.v1.NamedSparseSearchRequest\x1a\x1e.rostam.v1.NamedSearchResponse\x12R\n" +
	"\x11NamedHybridSearch\x12\x1d.rostam.v1.NamedHybridRequest\x1a\x1e.rostam.v1.NamedSearchResponse\x12T\n" +
	"\x0fNamedSearchDocs\x12\x1d.rostam.v1.NamedSearchRequest\x1a\".rostam.v1.NamedSearchDocsResponse\x12L\n" +
	"\vNamedDelete\x12\x1d.rostam.v1.NamedDeleteRequest\x1a\x1e.rostam.v1.NamedDeleteResponse\x12C\n" +
	"\bNamedGet\x12\x1a.rostam.v1.NamedGetRequest\x1a\x1b.rostam.v1.NamedGetResponse\x12R\n" +
	"\rNamedGetBatch\x12\x1f.rostam.v1.NamedGetBatchRequest\x1a .rostam.v1.NamedGetBatchResponse\x12K\n" +
	"\x0fNamedSetPayload\x12\x1c.rostam.v1.SetPayloadRequest\x1a\x1a.rostam.v1.PayloadResponse\x12Q\n" +
	"\x15NamedOverwritePayload\x12\x1c.rostam.v1.SetPayloadRequest\x1a\x1a.rostam.v1.PayloadResponse\x12Y\n" +
	"\x16NamedDeletePayloadKeys\x12#.rostam.v1.DeletePayloadKeysRequest\x1a\x1a.rostam.v1.PayloadResponse\x12O\n" +
	"\x11NamedClearPayload\x12\x1e.rostam.v1.ClearPayloadRequest\x1a\x1a.rostam.v1.PayloadResponse\x12L\n" +
	"\vNamedScroll\x12\x1d.rostam.v1.NamedScrollRequest\x1a\x1e.rostam.v1.NamedScrollResponse\x12=\n" +
	"\x06Scroll\x12\x18.rostam.v1.ScrollRequest\x1a\x19.rostam.v1.ScrollResponse\x12U\n" +
	"\x0eNamedGetConfig\x12 .rostam.v1.NamedGetConfigRequest\x1a!.rostam.v1.NamedGetConfigResponse\x12L\n" +
	"\vCreateAlias\x12\x1d.rostam.v1.CreateAliasRequest\x1a\x1e.rostam.v1.CreateAliasResponse\x12L\n" +
	"\vDeleteAlias\x12\x1d.rostam.v1.DeleteAliasRequest\x1a\x1e.rostam.v1.DeleteAliasResponse\x12L\n" +
	"\vListAliases\x12\x1d.rostam.v1.ListAliasesRequest\x1a\x1e.rostam.v1.ListAliasesResponse\x12I\n" +
	"\n" +
	"AliasBatch\x12\x1c.rostam.v1.AliasBatchRequest\x1a\x1d.rostam.v1.AliasBatchResponse\x128\n" +
	"\aKeysAdd\x12\x19.rostam.v1.KeysAddRequest\x1a\x12.rostam.v1.KeysAck\x12>\n" +
	"\n" +
	"KeysRevoke\x12\x1c.rostam.v1.KeysRevokeRequest\x1a\x12.rostam.v1.KeysAck\x12C\n" +
	"\bKeysList\x12\x1a.rostam.v1.KeysListRequest\x1a\x1b.rostam.v1.KeysListResponseB6Z4github.com/rostamlabs/rostam/grpcapi/grpcsvc;grpcsvcb\x06proto3"

var file_grpcapi_pb_service_proto_goTypes = []any{
	(*pb.HealthRequest)(nil),            // 0: rostam.v1.HealthRequest
	(*pb.CreateCollectionRequest)(nil),  // 1: rostam.v1.CreateCollectionRequest
	(*pb.DropCollectionRequest)(nil),    // 2: rostam.v1.DropCollectionRequest
	(*pb.UpsertRequest)(nil),            // 3: rostam.v1.UpsertRequest
	(*pb.DeleteRequest)(nil),            // 4: rostam.v1.DeleteRequest
	(*pb.GetRequest)(nil),               // 5: rostam.v1.GetRequest
	(*pb.GetBatchRequest)(nil),          // 6: rostam.v1.GetBatchRequest
	(*pb.SetPayloadRequest)(nil),        // 7: rostam.v1.SetPayloadRequest
	(*pb.DeletePayloadKeysRequest)(nil), // 8: rostam.v1.DeletePayloadKeysRequest
	(*pb.ClearPayloadRequest)(nil),      // 9: rostam.v1.ClearPayloadRequest
	(*pb.SearchRequest)(nil),            // 10: rostam.v1.SearchRequest
	(*pb.SearchGroupsRequest)(nil),      // 11: rostam.v1.SearchGroupsRequest
	(*pb.HybridRequest)(nil),            // 12: rostam.v1.HybridRequest
	(*pb.TextSearchRequest)(nil),        // 13: rostam.v1.TextSearchRequest
	(*pb.HybridTextRequest)(nil),        // 14: rostam.v1.HybridTextRequest
	(*pb.VectorQueryRequest)(nil),       // 15: rostam.v1.VectorQueryRequest
	(*pb.NamedVectorQueryRequest)(nil),  // 16: rostam.v1.NamedVectorQueryRequest
	(*pb.MVVectorQueryRequest)(nil),     // 17: rostam.v1.MVVectorQueryRequest
	(*pb.DeleteByFilterRequest)(nil),    // 18: rostam.v1.DeleteByFilterRequest
	(*pb.ResplitRequest)(nil),           // 19: rostam.v1.ResplitRequest
	(*pb.ResplitCleanupRequest)(nil),    // 20: rostam.v1.ResplitCleanupRequest
	(*pb.ReshardRequest)(nil),           // 21: rostam.v1.ReshardRequest
	(*pb.ReshardAbortRequest)(nil),      // 22: rostam.v1.ReshardAbortRequest
	(*pb.MVCreateRequest)(nil),          // 23: rostam.v1.MVCreateRequest
	(*pb.MVDropRequest)(nil),            // 24: rostam.v1.MVDropRequest
	(*pb.MVAddRequest)(nil),             // 25: rostam.v1.MVAddRequest
	(*pb.MVSearchRequest)(nil),          // 26: rostam.v1.MVSearchRequest
	(*pb.MVHybridRequest)(nil),          // 27: rostam.v1.MVHybridRequest
	(*pb.MVScrollRequest)(nil),          // 28: rostam.v1.MVScrollRequest
	(*pb.MVDeleteRequest)(nil),          // 29: rostam.v1.MVDeleteRequest
	(*pb.MVGetRequest)(nil),             // 30: rostam.v1.MVGetRequest
	(*pb.MVGetBatchRequest)(nil),        // 31: rostam.v1.MVGetBatchRequest
	(*pb.NamedCreateRequest)(nil),       // 32: rostam.v1.NamedCreateRequest
	(*pb.NamedDropRequest)(nil),         // 33: rostam.v1.NamedDropRequest
	(*pb.NamedUpsertRequest)(nil),       // 34: rostam.v1.NamedUpsertRequest
	(*pb.NamedSearchRequest)(nil),       // 35: rostam.v1.NamedSearchRequest
	(*pb.NamedSparseSearchRequest)(nil), // 36: rostam.v1.NamedSparseSearchRequest
	(*pb.NamedHybridRequest)(nil),       // 37: rostam.v1.NamedHybridRequest
	(*pb.NamedDeleteRequest)(nil),       // 38: rostam.v1.NamedDeleteRequest
	(*pb.NamedGetRequest)(nil),          // 39: rostam.v1.NamedGetRequest
	(*pb.NamedGetBatchRequest)(nil),     // 40: rostam.v1.NamedGetBatchRequest
	(*pb.NamedScrollRequest)(nil),       // 41: rostam.v1.NamedScrollRequest
	(*pb.ScrollRequest)(nil),            // 42: rostam.v1.ScrollRequest
	(*pb.NamedGetConfigRequest)(nil),    // 43: rostam.v1.NamedGetConfigRequest
	(*pb.CreateAliasRequest)(nil),       // 44: rostam.v1.CreateAliasRequest
	(*pb.DeleteAliasRequest)(nil),       // 45: rostam.v1.DeleteAliasRequest
	(*pb.ListAliasesRequest)(nil),       // 46: rostam.v1.ListAliasesRequest
	(*pb.AliasBatchRequest)(nil),        // 47: rostam.v1.AliasBatchRequest
	(*pb.KeysAddRequest)(nil),           // 48: rostam.v1.KeysAddRequest
	(*pb.KeysRevokeRequest)(nil),        // 49: rostam.v1.KeysRevokeRequest
	(*pb.KeysListRequest)(nil),          // 50: rostam.v1.KeysListRequest
	(*pb.HealthResponse)(nil),           // 51: rostam.v1.HealthResponse
	(*pb.CreateCollectionResponse)(nil), // 52: rostam.v1.CreateCollectionResponse
	(*pb.DropCollectionResponse)(nil),   // 53: rostam.v1.DropCollectionResponse
	(*pb.UpsertResponse)(nil),           // 54: rostam.v1.UpsertResponse
	(*pb.DeleteResponse)(nil),           // 55: rostam.v1.DeleteResponse
	(*pb.GetResponse)(nil),              // 56: rostam.v1.GetResponse
	(*pb.GetBatchResponse)(nil),         // 57: rostam.v1.GetBatchResponse
	(*pb.PayloadResponse)(nil),          // 58: rostam.v1.PayloadResponse
	(*pb.SearchResponse)(nil),           // 59: rostam.v1.SearchResponse
	(*pb.SearchDocsResponse)(nil),       // 60: rostam.v1.SearchDocsResponse
	(*pb.SearchGroupsResponse)(nil),     // 61: rostam.v1.SearchGroupsResponse
	(*pb.DeleteByFilterResponse)(nil),   // 62: rostam.v1.DeleteByFilterResponse
	(*pb.ResplitResponse)(nil),          // 63: rostam.v1.ResplitResponse
	(*pb.ResplitCleanupResponse)(nil),   // 64: rostam.v1.ResplitCleanupResponse
	(*pb.ReshardResponse)(nil),          // 65: rostam.v1.ReshardResponse
	(*pb.ReshardAbortResponse)(nil),     // 66: rostam.v1.ReshardAbortResponse
	(*pb.MVCreateResponse)(nil),         // 67: rostam.v1.MVCreateResponse
	(*pb.MVDropResponse)(nil),           // 68: rostam.v1.MVDropResponse
	(*pb.MVAddResponse)(nil),            // 69: rostam.v1.MVAddResponse
	(*pb.MVSearchResponse)(nil),         // 70: rostam.v1.MVSearchResponse
	(*pb.NamedSearchResponse)(nil),      // 71: rostam.v1.NamedSearchResponse
	(*pb.MVScrollResponse)(nil),         // 72: rostam.v1.MVScrollResponse
	(*pb.MVDeleteResponse)(nil),         // 73: rostam.v1.MVDeleteResponse
	(*pb.MVGetResponse)(nil),            // 74: rostam.v1.MVGetResponse
	(*pb.MVGetBatchResponse)(nil),       // 75: rostam.v1.MVGetBatchResponse
	(*pb.NamedCreateResponse)(nil),      // 76: rostam.v1.NamedCreateResponse
	(*pb.NamedDropResponse)(nil),        // 77: rostam.v1.NamedDropResponse
	(*pb.NamedUpsertResponse)(nil),      // 78: rostam.v1.NamedUpsertResponse
	(*pb.NamedSearchDocsResponse)(nil),  // 79: rostam.v1.NamedSearchDocsResponse
	(*pb.NamedDeleteResponse)(nil),      // 80: rostam.v1.NamedDeleteResponse
	(*pb.NamedGetResponse)(nil),         // 81: rostam.v1.NamedGetResponse
	(*pb.NamedGetBatchResponse)(nil),    // 82: rostam.v1.NamedGetBatchResponse
	(*pb.NamedScrollResponse)(nil),      // 83: rostam.v1.NamedScrollResponse
	(*pb.ScrollResponse)(nil),           // 84: rostam.v1.ScrollResponse
	(*pb.NamedGetConfigResponse)(nil),   // 85: rostam.v1.NamedGetConfigResponse
	(*pb.CreateAliasResponse)(nil),      // 86: rostam.v1.CreateAliasResponse
	(*pb.DeleteAliasResponse)(nil),      // 87: rostam.v1.DeleteAliasResponse
	(*pb.ListAliasesResponse)(nil),      // 88: rostam.v1.ListAliasesResponse
	(*pb.AliasBatchResponse)(nil),       // 89: rostam.v1.AliasBatchResponse
	(*pb.KeysAck)(nil),                  // 90: rostam.v1.KeysAck
	(*pb.KeysListResponse)(nil),         // 91: rostam.v1.KeysListResponse
}
var file_grpcapi_pb_service_proto_depIdxs = []int32{
	0,  // 0: rostam.v1.VectorService.Health:input_type -> rostam.v1.HealthRequest
	1,  // 1: rostam.v1.VectorService.CreateCollection:input_type -> rostam.v1.CreateCollectionRequest
	2,  // 2: rostam.v1.VectorService.DropCollection:input_type -> rostam.v1.DropCollectionRequest
	3,  // 3: rostam.v1.VectorService.Upsert:input_type -> rostam.v1.UpsertRequest
	4,  // 4: rostam.v1.VectorService.Delete:input_type -> rostam.v1.DeleteRequest
	5,  // 5: rostam.v1.VectorService.Get:input_type -> rostam.v1.GetRequest
	6,  // 6: rostam.v1.VectorService.GetBatch:input_type -> rostam.v1.GetBatchRequest
	7,  // 7: rostam.v1.VectorService.SetPayload:input_type -> rostam.v1.SetPayloadRequest
	7,  // 8: rostam.v1.VectorService.OverwritePayload:input_type -> rostam.v1.SetPayloadRequest
	8,  // 9: rostam.v1.VectorService.DeletePayloadKeys:input_type -> rostam.v1.DeletePayloadKeysRequest
	9,  // 10: rostam.v1.VectorService.ClearPayload:input_type -> rostam.v1.ClearPayloadRequest
	10, // 11: rostam.v1.VectorService.Search:input_type -> rostam.v1.SearchRequest
	10, // 12: rostam.v1.VectorService.SearchDocs:input_type -> rostam.v1.SearchRequest
	11, // 13: rostam.v1.VectorService.SearchGroups:input_type -> rostam.v1.SearchGroupsRequest
	12, // 14: rostam.v1.VectorService.HybridSearch:input_type -> rostam.v1.HybridRequest
	13, // 15: rostam.v1.VectorService.TextSearch:input_type -> rostam.v1.TextSearchRequest
	14, // 16: rostam.v1.VectorService.HybridTextSearch:input_type -> rostam.v1.HybridTextRequest
	15, // 17: rostam.v1.VectorService.VectorQuery:input_type -> rostam.v1.VectorQueryRequest
	16, // 18: rostam.v1.VectorService.NamedVectorQuery:input_type -> rostam.v1.NamedVectorQueryRequest
	17, // 19: rostam.v1.VectorService.MVVectorQuery:input_type -> rostam.v1.MVVectorQueryRequest
	18, // 20: rostam.v1.VectorService.DeleteByFilter:input_type -> rostam.v1.DeleteByFilterRequest
	19, // 21: rostam.v1.VectorService.Resplit:input_type -> rostam.v1.ResplitRequest
	20, // 22: rostam.v1.VectorService.ResplitCleanup:input_type -> rostam.v1.ResplitCleanupRequest
	21, // 23: rostam.v1.VectorService.Reshard:input_type -> rostam.v1.ReshardRequest
	22, // 24: rostam.v1.VectorService.ReshardAbort:input_type -> rostam.v1.ReshardAbortRequest
	23, // 25: rostam.v1.VectorService.MVCreateCollection:input_type -> rostam.v1.MVCreateRequest
	24, // 26: rostam.v1.VectorService.MVDropCollection:input_type -> rostam.v1.MVDropRequest
	25, // 27: rostam.v1.VectorService.MVAdd:input_type -> rostam.v1.MVAddRequest
	26, // 28: rostam.v1.VectorService.MVSearch:input_type -> rostam.v1.MVSearchRequest
	27, // 29: rostam.v1.VectorService.MVHybridSearch:input_type -> rostam.v1.MVHybridRequest
	28, // 30: rostam.v1.VectorService.MVScroll:input_type -> rostam.v1.MVScrollRequest
	29, // 31: rostam.v1.VectorService.MVDelete:input_type -> rostam.v1.MVDeleteRequest
	30, // 32: rostam.v1.VectorService.MVGet:input_type -> rostam.v1.MVGetRequest
	31, // 33: rostam.v1.VectorService.MVGetBatch:input_type -> rostam.v1.MVGetBatchRequest
	7,  // 34: rostam.v1.VectorService.MVSetPayload:input_type -> rostam.v1.SetPayloadRequest
	7,  // 35: rostam.v1.VectorService.MVOverwritePayload:input_type -> rostam.v1.SetPayloadRequest
	8,  // 36: rostam.v1.VectorService.MVDeletePayloadKeys:input_type -> rostam.v1.DeletePayloadKeysRequest
	9,  // 37: rostam.v1.VectorService.MVClearPayload:input_type -> rostam.v1.ClearPayloadRequest
	19, // 38: rostam.v1.VectorService.MVResplit:input_type -> rostam.v1.ResplitRequest
	20, // 39: rostam.v1.VectorService.MVResplitCleanup:input_type -> rostam.v1.ResplitCleanupRequest
	21, // 40: rostam.v1.VectorService.MVReshard:input_type -> rostam.v1.ReshardRequest
	22, // 41: rostam.v1.VectorService.MVReshardAbort:input_type -> rostam.v1.ReshardAbortRequest
	32, // 42: rostam.v1.VectorService.NamedCreate:input_type -> rostam.v1.NamedCreateRequest
	33, // 43: rostam.v1.VectorService.NamedDrop:input_type -> rostam.v1.NamedDropRequest
	34, // 44: rostam.v1.VectorService.NamedUpsert:input_type -> rostam.v1.NamedUpsertRequest
	35, // 45: rostam.v1.VectorService.NamedSearch:input_type -> rostam.v1.NamedSearchRequest
	36, // 46: rostam.v1.VectorService.NamedSparseSearch:input_type -> rostam.v1.NamedSparseSearchRequest
	37, // 47: rostam.v1.VectorService.NamedHybridSearch:input_type -> rostam.v1.NamedHybridRequest
	35, // 48: rostam.v1.VectorService.NamedSearchDocs:input_type -> rostam.v1.NamedSearchRequest
	38, // 49: rostam.v1.VectorService.NamedDelete:input_type -> rostam.v1.NamedDeleteRequest
	39, // 50: rostam.v1.VectorService.NamedGet:input_type -> rostam.v1.NamedGetRequest
	40, // 51: rostam.v1.VectorService.NamedGetBatch:input_type -> rostam.v1.NamedGetBatchRequest
	7,  // 52: rostam.v1.VectorService.NamedSetPayload:input_type -> rostam.v1.SetPayloadRequest
	7,  // 53: rostam.v1.VectorService.NamedOverwritePayload:input_type -> rostam.v1.SetPayloadRequest
	8,  // 54: rostam.v1.VectorService.NamedDeletePayloadKeys:input_type -> rostam.v1.DeletePayloadKeysRequest
	9,  // 55: rostam.v1.VectorService.NamedClearPayload:input_type -> rostam.v1.ClearPayloadRequest
	41, // 56: rostam.v1.VectorService.NamedScroll:input_type -> rostam.v1.NamedScrollRequest
	42, // 57: rostam.v1.VectorService.Scroll:input_type -> rostam.v1.ScrollRequest
	43, // 58: rostam.v1.VectorService.NamedGetConfig:input_type -> rostam.v1.NamedGetConfigRequest
	44, // 59: rostam.v1.VectorService.CreateAlias:input_type -> rostam.v1.CreateAliasRequest
	45, // 60: rostam.v1.VectorService.DeleteAlias:input_type -> rostam.v1.DeleteAliasRequest
	46, // 61: rostam.v1.VectorService.ListAliases:input_type -> rostam.v1.ListAliasesRequest
	47, // 62: rostam.v1.VectorService.AliasBatch:input_type -> rostam.v1.AliasBatchRequest
	48, // 63: rostam.v1.VectorService.KeysAdd:input_type -> rostam.v1.KeysAddRequest
	49, // 64: rostam.v1.VectorService.KeysRevoke:input_type -> rostam.v1.KeysRevokeRequest
	50, // 65: rostam.v1.VectorService.KeysList:input_type -> rostam.v1.KeysListRequest
	51, // 66: rostam.v1.VectorService.Health:output_type -> rostam.v1.HealthResponse
	52, // 67: rostam.v1.VectorService.CreateCollection:output_type -> rostam.v1.CreateCollectionResponse
	53, // 68: rostam.v1.VectorService.DropCollection:output_type -> rostam.v1.DropCollectionResponse
	54, // 69: rostam.v1.VectorService.Upsert:output_type -> rostam.v1.UpsertResponse
	55, // 70: rostam.v1.VectorService.Delete:output_type -> rostam.v1.DeleteResponse
	56, // 71: rostam.v1.VectorService.Get:output_type -> rostam.v1.GetResponse
	57, // 72: rostam.v1.VectorService.GetBatch:output_type -> rostam.v1.GetBatchResponse
	58, // 73: rostam.v1.VectorService.SetPayload:output_type -> rostam.v1.PayloadResponse
	58, // 74: rostam.v1.VectorService.OverwritePayload:output_type -> rostam.v1.PayloadResponse
	58, // 75: rostam.v1.VectorService.DeletePayloadKeys:output_type -> rostam.v1.PayloadResponse
	58, // 76: rostam.v1.VectorService.ClearPayload:output_type -> rostam.v1.PayloadResponse
	59, // 77: rostam.v1.VectorService.Search:output_type -> rostam.v1.SearchResponse
	60, // 78: rostam.v1.VectorService.SearchDocs:output_type -> rostam.v1.SearchDocsResponse
	61, // 79: rostam.v1.VectorService.SearchGroups:output_type -> rostam.v1.SearchGroupsResponse
	59, // 80: rostam.v1.VectorService.HybridSearch:output_type -> rostam.v1.SearchResponse
	60, // 81: rostam.v1.VectorService.TextSearch:output_type -> rostam.v1.SearchDocsResponse
	59, // 82: rostam.v1.VectorService.HybridTextSearch:output_type -> rostam.v1.SearchResponse
	59, // 83: rostam.v1.VectorService.VectorQuery:output_type -> rostam.v1.SearchResponse
	59, // 84: rostam.v1.VectorService.NamedVectorQuery:output_type -> rostam.v1.SearchResponse
	59, // 85: rostam.v1.VectorService.MVVectorQuery:output_type -> rostam.v1.SearchResponse
	62, // 86: rostam.v1.VectorService.DeleteByFilter:output_type -> rostam.v1.DeleteByFilterResponse
	63, // 87: rostam.v1.VectorService.Resplit:output_type -> rostam.v1.ResplitResponse
	64, // 88: rostam.v1.VectorService.ResplitCleanup:output_type -> rostam.v1.ResplitCleanupResponse
	65, // 89: rostam.v1.VectorService.Reshard:output_type -> rostam.v1.ReshardResponse
	66, // 90: rostam.v1.VectorService.ReshardAbort:output_type -> rostam.v1.ReshardAbortResponse
	67, // 91: rostam.v1.VectorService.MVCreateCollection:output_type -> rostam.v1.MVCreateResponse
	68, // 92: rostam.v1.VectorService.MVDropCollection:output_type -> rostam.v1.MVDropResponse
	69, // 93: rostam.v1.VectorService.MVAdd:output_type -> rostam.v1.MVAddResponse
	70, // 94: rostam.v1.VectorService.MVSearch:output_type -> rostam.v1.MVSearchResponse
	71, // 95: rostam.v1.VectorService.MVHybridSearch:output_type -> rostam.v1.NamedSearchResponse
	72, // 96: rostam.v1.VectorService.MVScroll:output_type -> rostam.v1.MVScrollResponse
	73, // 97: rostam.v1.VectorService.MVDelete:output_type -> rostam.v1.MVDeleteResponse
	74, // 98: rostam.v1.VectorService.MVGet:output_type -> rostam.v1.MVGetResponse
	75, // 99: rostam.v1.VectorService.MVGetBatch:output_type -> rostam.v1.MVGetBatchResponse
	58, // 100: rostam.v1.VectorService.MVSetPayload:output_type -> rostam.v1.PayloadResponse
	58, // 101: rostam.v1.VectorService.MVOverwritePayload:output_type -> rostam.v1.PayloadResponse
	58, // 102: rostam.v1.VectorService.MVDeletePayloadKeys:output_type -> rostam.v1.PayloadResponse
	58, // 103: rostam.v1.VectorService.MVClearPayload:output_type -> rostam.v1.PayloadResponse
	63, // 104: rostam.v1.VectorService.MVResplit:output_type -> rostam.v1.ResplitResponse
	64, // 105: rostam.v1.VectorService.MVResplitCleanup:output_type -> rostam.v1.ResplitCleanupResponse
	65, // 106: rostam.v1.VectorService.MVReshard:output_type -> rostam.v1.ReshardResponse
	66, // 107: rostam.v1.VectorService.MVReshardAbort:output_type -> rostam.v1.ReshardAbortResponse
	76, // 108: rostam.v1.VectorService.NamedCreate:output_type -> rostam.v1.NamedCreateResponse
	77, // 109: rostam.v1.VectorService.NamedDrop:output_type -> rostam.v1.NamedDropResponse
	78, // 110: rostam.v1.VectorService.NamedUpsert:output_type -> rostam.v1.NamedUpsertResponse
	71, // 111: rostam.v1.VectorService.NamedSearch:output_type -> rostam.v1.NamedSearchResponse
	71, // 112: rostam.v1.VectorService.NamedSparseSearch:output_type -> rostam.v1.NamedSearchResponse
	71, // 113: rostam.v1.VectorService.NamedHybridSearch:output_type -> rostam.v1.NamedSearchResponse
	79, // 114: rostam.v1.VectorService.NamedSearchDocs:output_type -> rostam.v1.NamedSearchDocsResponse
	80, // 115: rostam.v1.VectorService.NamedDelete:output_type -> rostam.v1.NamedDeleteResponse
	81, // 116: rostam.v1.VectorService.NamedGet:output_type -> rostam.v1.NamedGetResponse
	82, // 117: rostam.v1.VectorService.NamedGetBatch:output_type -> rostam.v1.NamedGetBatchResponse
	58, // 118: rostam.v1.VectorService.NamedSetPayload:output_type -> rostam.v1.PayloadResponse
	58, // 119: rostam.v1.VectorService.NamedOverwritePayload:output_type -> rostam.v1.PayloadResponse
	58, // 120: rostam.v1.VectorService.NamedDeletePayloadKeys:output_type -> rostam.v1.PayloadResponse
	58, // 121: rostam.v1.VectorService.NamedClearPayload:output_type -> rostam.v1.PayloadResponse
	83, // 122: rostam.v1.VectorService.NamedScroll:output_type -> rostam.v1.NamedScrollResponse
	84, // 123: rostam.v1.VectorService.Scroll:output_type -> rostam.v1.ScrollResponse
	85, // 124: rostam.v1.VectorService.NamedGetConfig:output_type -> rostam.v1.NamedGetConfigResponse
	86, // 125: rostam.v1.VectorService.CreateAlias:output_type -> rostam.v1.CreateAliasResponse
	87, // 126: rostam.v1.VectorService.DeleteAlias:output_type -> rostam.v1.DeleteAliasResponse
	88, // 127: rostam.v1.VectorService.ListAliases:output_type -> rostam.v1.ListAliasesResponse
	89, // 128: rostam.v1.VectorService.AliasBatch:output_type -> rostam.v1.AliasBatchResponse
	90, // 129: rostam.v1.VectorService.KeysAdd:output_type -> rostam.v1.KeysAck
	90, // 130: rostam.v1.VectorService.KeysRevoke:output_type -> rostam.v1.KeysAck
	91, // 131: rostam.v1.VectorService.KeysList:output_type -> rostam.v1.KeysListResponse
	66, // [66:132] is the sub-list for method output_type
	0,  // [0:66] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_grpcapi_pb_service_proto_init() }
func file_grpcapi_pb_service_proto_init() {
	if File_grpcapi_pb_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcapi_pb_service_proto_rawDesc), len(file_grpcapi_pb_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcapi_pb_service_proto_goTypes,
		DependencyIndexes: file_grpcapi_pb_service_proto_depIdxs,
	}.Build()
	File_grpcapi_pb_service_proto = out.File
	file_grpcapi_pb_service_proto_goTypes = nil
	file_grpcapi_pb_service_proto_depIdxs = nil
}
