"""Byte-for-byte differential test of the Python vector encoders vs the Go
reference.

The vector op arg layouts — especially create_collection's config trailer, with
its forced-presence chain — are fragile: a single field-order or type slip
produces a malformed request the server may accept and misinterpret. So rather
than trust a reading of the Go encoder, this asserts the Python output is
byte-identical to what Go's ops.Encode*Args produced, for a matrix of configs.

The golden fixtures live in _oracle/golden.txt, generated by _oracle/main.go:

    go run ./clients/python/tests/_oracle > clients/python/tests/_oracle/golden.txt

Regenerate them whenever an encoder changes; a drift here means the Python
client and the Go server have stopped agreeing on the wire.

Only the fixed-binary ops are byte-checked. Ops whose tail is embedded JSON
(metadata, filter, content) are covered by the cross-stack round-trip instead,
because the server unmarshals that JSON and any equivalent encoding decodes the
same — byte-identity there would over-constrain to Go's exact key order.
"""

from __future__ import annotations

import os
import unittest

from rostam import _vecwire as w

_GOLDEN = os.path.join(os.path.dirname(__file__), "_oracle", "golden.txt")


def _load():
    out = {}
    with open(_GOLDEN) as f:
        for line in f:
            name, hexv = line.strip().split("\t")
            out[name] = hexv
    return out


_BASE = dict(dim=8, metric="cosine", m=16, ef_construction=200, ef_search=64)

# name -> (collection, cfg) for every create_collection golden case
_CREATE = {
    "create/basic": ("docs", _BASE),
    "create/l2_seed": ("docs", {**_BASE, "metric": "l2", "seed": 42}),
    "create/sq8": ("c-sq8", {**_BASE, "quant": "sq8"}),
    "create/bq1": ("c", {**_BASE, "quant": "bq1"}),
    "create/persistent_rescore": ("p", {**_BASE, "persistent": True, "rescore_factor": 3}),
    "create/partitions": ("part", {**_BASE, "partitions": 4}),
    "create/hnsw_levers": ("lev", {**_BASE, "extend_candidates": True, "extend_candidates_max": 200,
                                   "level0_full_degree": True, "quantized_build": True}),
    "create/ivf": ("ivf", {**_BASE, "index_type": "ivf", "ivf_nlist": 64, "ivf_nprobe": 8}),
    "create/vamana": ("vam", {**_BASE, "index_type": "vamana", "vamana_r": 64, "vamana_l": 100, "vamana_alpha": 1.2}),
    "create/fulltext": ("ft", {**_BASE, "full_text": {"analyzer": "english", "k1": 1.2, "b": 0.75}}),
    "create/tuned": ("longname-collection", {**_BASE, "dim": 128, "m": 32, "ef_construction": 400, "ef_search": 128}),
    "create/aniso": ("an", {**_BASE, "anisotropic_eta": 0.2}),
    "create/soar": ("so", {**_BASE, "soar": True, "soar_lambda": 1.5}),
    "create/sqbits": ("sq", {**_BASE, "quant": "sq", "sq_bits": 6}),
    "create/ivf_threshold": ("ivt", {**_BASE, "index_type": "ivf", "ivf_train_threshold": 10000}),
}

_VEC = [0.1, 0.2, 0.3, 0.4]

# name -> callable producing the bytes, for fixed-binary data-plane ops
_DATAPLANE = {
    "insert/plain": lambda: w.encode_insert_args("docs", 1, _VEC),
    "insert/sparse": lambda: w.encode_insert_args("docs", 9, _VEC,
                                                  sparse={"indices": [3, 17], "values": [0.8, 0.4]}),
    "search/plain": lambda: w.encode_search_args("docs", 10, _VEC),
    "delete": lambda: w.encode_delete_args("docs", 42),
    "exists": lambda: w.encode_exists_args("docs", 42),
    "get/plain": lambda: w.encode_get_args("docs", 1, 0),
    "get/withvec_payload": lambda: w.encode_get_args("docs", 1, 0x03),
}


class VecwireGoldenTest(unittest.TestCase):
    def setUp(self):
        self.golden = _load()

    def test_create_collection_matches_go(self):
        for name, (col, cfg) in _CREATE.items():
            with self.subTest(name=name):
                got = w.encode_create_collection_args(col, cfg).hex()
                self.assertEqual(got, self.golden[name], f"{name} diverged from the Go encoder")

    def test_dataplane_binary_matches_go(self):
        for name, fn in _DATAPLANE.items():
            with self.subTest(name=name):
                self.assertEqual(fn().hex(), self.golden[name], f"{name} diverged from the Go encoder")

    def test_metadata_prefix_matches_and_json_equivalent(self):
        # insert/ttl_meta: the binary prefix must match Go exactly; the metadata
        # JSON tail need only decode to the same object.
        import json
        want = bytes.fromhex(self.golden["insert/ttl_meta"])
        got = w.encode_insert_args("docs", 7, _VEC, ttl_ms=300000,
                                   metadata={"tenant": "acme", "year": 2020})
        head = 1 + (1 + len("docs")) + 8 + 4 + 4 * len(_VEC) + 8  # flags+col+id+dim+vec+ttl
        self.assertEqual(got[:head], want[:head], "insert binary prefix diverged")
        self.assertEqual(json.loads(got[head + 4:]), json.loads(want[head + 4:]),
                         "metadata JSON is not equivalent to Go's")


class VecwireGuardTest(unittest.TestCase):
    def test_reserved_content_key_rejected(self):
        # $content is how upsert folds the content string into the metadata JSON;
        # letting a caller set it would silently override (or forge) content.
        with self.assertRaises(ValueError):
            w.encode_upsert_args("docs", 1, _VEC, content="hi",
                                 metadata={"$content": "sneaky"})
        with self.assertRaises(ValueError):
            w.encode_insert_args("docs", 1, _VEC, metadata={"$content": "sneaky"})

    def test_sparse_length_mismatch_rejected(self):
        # Unequal indices/values would write a count for the longer list but
        # zip only the shorter — a malformed, truncated binary payload.
        with self.assertRaises(ValueError):
            w.encode_insert_args("docs", 1, _VEC,
                                 sparse={"indices": [1, 2, 3], "values": [0.5, 0.5]})


if __name__ == "__main__":
    unittest.main()
